- name: Remove old ami
  hosts: localhost
  gather_facts: no
  tasks:

    - ec2_ami_find:
        region: "{{ region }}"
        ami_tags:
          Name: "{{ prefix }}-docker-node-template"
      register: ami_found

    - ec2_ami:
        region: "{{ region }}"
        image_id: "{{ ami_found.results[0].ami_id }}"
        delete_snapshot: yes
        state: absent
